on: push

jobs:
  build-debs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: leonheldattoradex/build-deb-action@v1.7.1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: --build=binary --no-sign
          host-arch: arm64
          apt-opts: --install-recommends

      - name: Run piuparts test
        uses: evgeni/action-piuparts@b6520bd02312076d3148b57ff3109dea1145bf0d
        with:
          package: debian/artifacts/*.changes
          base-image: debian:bookworm
          distribution: bookworm
